### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by meprazhant** [ABChapagain/CRUD-REACT-MYSQL-NODEJS#1]
REACT_NODE ma SQL ramro lagyo ki MongoDB?

**Comment by ABChapagain** [comment]
Kasto khalko project ho tesma depend garxa. Small size xa tables or collections bich dherai relation xaina vane mysql thik hunxa no need to use mongoDB but, dherai collection haru xa relations haru dherai baninxa vane mysql use garna garo hunxa so better to use mongoDB

**Comment by meprazhant** [comment]
ea nice nicew
